<a href="https://colab.research.google.com/github/ankitha-km/Code_Crusaders_75/blob/main/Student_Performance_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    "study_hours": [2, 4, 6, 8, 1, 3, 7, 5, 9, 4],
    "attendance": [60, 70, 80, 90, 50, 65, 85, 75, 95, 72],
    "previous_marks": [45, 55, 65, 78, 40, 50, 72, 68, 88, 60],
    "sleep_hours": [6, 7, 8, 7, 5, 6, 8, 7, 8, 6],
    "pass": [0, 0, 1, 1, 0, 0, 1, 1, 1, 1]  # 0 = Fail, 1 = Pass
}

df = pd.DataFrame(data)
df

   study_hours  attendance  previous_marks  sleep_hours  pass
0            2          60              45            6     0
1            4          70              55            7     0
2            6          80              65            8     1
3            8          90              78            7     1
4            1          50              40            5     0
5            3          65              50            6     0
6            7          85              72            8     1
7            5          75              68            7     1
8            9          95              88            8     1
9            4          72              60            6     1

split input and output

 now add cell 2
 input features (X) and target y

  the model must learn to predict the pass or fail using all inputs like study hours, attendence , prev marks, sleep hours ..

  takes df(whole dataset)
  removes the pass col
  keeps only input data  // so now X contain only questions.

  y=df["pass"] // takes only pass col and stores it separately


  this we are doing -- splitting data into training and testing.
  first learn and then prove what it learned

In [ ]:
X = df.drop("pass", axis=1)
y = df["pass"]

X, y

(   study_hours  attendance  previous_marks  sleep_hours
 0            2          60              45            6
 1            4          70              55            7
 2            6          80              65            8
 3            8          90              78            7
 4            1          50              40            5
 5            3          65              50            6
 6            7          85              72            8
 7            5          75              68            7
 8            9          95              88            8
 9            4          72              60            6,
 0    0
 1    0
 2    1
 3    1
 4    0
 5    0
 6    1
 7    1
 8    1
 9    1
 Name: pass, dtype: int64)

train and split
train data to teach model
split data to check if it learned properly

we are importing a ready made function this function automatically divides data so no manual work needed

train_test_split(X, y, ...)

test_size=0.2

This decides how much data is for exam.

0.2 = 20% testing

0.8 = 80% training

random_state=42 ---> “Shuffle data in the SAME way every time.”

scikit-learn is a Python library made specially for:
Machine Learning
Data analysis
Model evaluation

Suppose:

First rows = old students

Last rows = recent students

Without shuffle:

Train = old patterns

Test = new patterns

Model fails because:

It never saw similar data during training

why == Model memorizes pattern of ordered data

Gives fake high accuracy

 we split as test and train ..the model sees iput data as train data  80%
 and model never seen the test data 20%
 finally we check it
 the order is broken

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train, X_test, y_train, y_test

(   study_hours  attendance  previous_marks  sleep_hours
 5            3          65              50            6
 0            2          60              45            6
 7            5          75              68            7
 2            6          80              65            8
 9            4          72              60            6
 4            1          50              40            5
 3            8          90              78            7
 6            7          85              72            8,
    study_hours  attendance  previous_marks  sleep_hours
 8            9          95              88            8
 1            4          70              55            7,
 5    0
 0    0
 7    1
 2    1
 9    1
 4    0
 3    1
 6    1
 Name: pass, dtype: int64,
 8    1
 1    0
 Name: pass, dtype: int64)

train ML model
 use logistic regression to train because - it is used for yes or no problems ,beginner friendly, industry standard ,perfect for pass  or fail


 model = LogisticRegression()
→ Created an empty brain 🧠

model.fit(X_train, y_train)
→ Model studied:

study hours

attendance

previous marks

sleep hours
and learned how they relate to pass/fail

This is called:

Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression

#create model
model = LogisticRegression()

#train model
model.fit(X_train, y_train)

LogisticRegression()

Make Predictions

In [ ]:
y_pred = model.predict(X_test)

y_pred

array([1, 1])

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.5

In [ ]:
# Compare predictions with actual results
comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

comparison

   Actual  Predicted
8       1          1
1       0          1